### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by deafwood** [vincenzorm117/node_google_oauth2_passport_example#1]
I was able git clone your code and insert my Google API credentials into your example, however, in the very last step while attempting to access /auth/google/callback, it returned the following error:

> Error
>     at /Users/scott/Code/googlelogin/node_modules/passport-google-oauth20/lib/strategy.js:95:21
>     at passBackControl (/Users/scott/Code/googlelogin/node_modules/oauth/lib/oauth2.js:132:9)
>     at IncomingMessage.<anonymous> (/Users/scott/Code/googlelogin/node_modules/oauth/lib/oauth2.js:157:7)
>     at emitNone (events.js:110:20)
>     at IncomingMessage.emit (events.js:207:7)
>     at endReadableNT (_stream_readable.js:1059:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

I'm a newbie in NodeJS/ExpressJS and am not sure how to debug this issue.  Can you determine if this is an error with your code or an error on my part?  Any suggestions you can give me would be appreciated!

**Comment by deafwood** [comment]
Problem solved -- needed to enable Google+ API for this to work.

**Comment by vincenzorm117** [comment]
Just to confirm, that was the issue. Turned it on and everything worked.
